# This docker-compose file will spin up a postgres database for use.
version: '3'
services:
  # PostgreSQL container for veritas internal storage
  postgres:
    build: "postgres/"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    env_file:
      - postgres/.env
    ports:
      # map to 5433 to prevent interference with local installation of postgres
      - "5433:5432"
  # flask server for application
  app:
    build: "app/"
    ports:
      - "5000:5000"
    command: flask run --host=0.0.0.0
volumes:
  postgres:
